### ISSUE TITLE
Crowsnest stopped working and will not reinstall

### ISSUE THREAD

**Issue by imar014** [mainsail-crew/crowsnest#100]
### What happened

Raspberry Pi installation of Mainsail using kiauh. Debian update seems to have broken MMAL dependencies. Uninstalled and reinstalled as Crowsnest not starting. 

Several attempts always show same error. Output during installation pasted below

Linux mainsail 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar 22 12:30:18 2023 from 192.168.5.3
iain@mainsail:~ $ cd kiauh
iain@mainsail:~/kiauh $ ./kiauh.sh
/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/
/=======================================================\
| Please read the newest changelog carefully:           |
| https://git.io/JnmlX                                  |
\=======================================================/
/=======================================================\
|     ~~~~~~~~~~~~~~~ [ Main Menu ] ~~~~~~~~~~~~~~~     |
|-------------------------------------------------------|
|  0) [Log-Upload] |         Klipper: Installed: 1(py3) |
|                  |            Repo: Klipper3d/klipper |
|  1) [Install]    |                                    |
|  2) [Update]     |       Moonraker: Installed: 1      |
|  3) [Remove]     |                                    |
|  4) [Advanced]   |        Mainsail: Installed!        |
|                  |          Fluidd: Not installed!    |
|                  |   KlipperScreen: Installed!        |
|  6) [Settings]   |    Telegram Bot: Not installed!    |
|                  |       Crowsnest: Incomplete!       |
|                  |           Obico: Not installed!    |
|                  |  OctoEverywhere: Not installed!    |
|                  |                                    |
|  v5.0.0-33       |       Octoprint: Not installed!    |
|-------------------------------------------------------|
|                        Q) Quit                        |
\=======================================================/
####### Perform action: 1
/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/
/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/
/=======================================================\
|     ~~~~~~~~~~~ [ Installation Menu ] ~~~~~~~~~~~     |
|-------------------------------------------------------|
|  You need this menu usually only for installing       |
|  all necessary dependencies for the various           |
|  functions on a completely fresh system.              |
|-------------------------------------------------------|
| Firmware & API:          | 3rd Party Webinterface:    |
|  1) [Klipper]            |  6) [OctoPrint]            |
|  2) [Moonraker]          |                            |
|                          | Other:                     |
| Klipper Webinterface:    |  7) [PrettyGCode]          |
|  3) [Mainsail]           |  8) [Telegram Bot]         |
|  4) [Fluidd]             |  9) [Obico for Klipper]    |
|                          | 10) [OctoEverywhere]       |
| Touchscreen GUI:         |                            |
|  5) [KlipperScreen]      | Webcam Streamer:           |
|                          | 11) [Crowsnest]            |
|-------------------------------------------------------|
|                       B) « Back                       |
\=======================================================/
####### Perform action: 11
/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/

###### Cloning 'crowsnest' repository ...
[✓ OK] crowsnest repository already exists ...

###### Checking for the following dependencies:
● git 
● make 
[✓ OK] Dependencies already met!
Installer will prompt you for sudo password!

###### Launching crowsnest installer ...
[sudo] password for iain: 
crowsnest - A webcam daemon for multiple Cams and stream services.

        Ahoi!
        Thank you for installing crowsnest ;)
        This will take a while ... 
        Please reboot after installation has finished.

Running apt update first ...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
Installing 'crowsnest' Dependencies ...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
crudini is already the newest version (0.9.3-4).
findutils is already the newest version (4.8.0-1).
libbsd-dev is already the newest version (0.11.3-1).
libevent-dev is already the newest version (2.1.12-stable-1).
libjpeg-dev is already the newest version (1:2.0.6-4).
libxcomposite1 is already the newest version (1:0.4.5-1).
libxtst6 is already the newest version (2:1.2.3-1).
bsdutils is already the newest version (1:2.36.1-8+deb11u1).
v4l-utils is already the newest version (1.20.0-2).
curl is already the newest version (7.74.0-1.3+deb11u7).
git is already the newest version (1:2.30.2-1+deb11u2).
ffmpeg is already the newest version (7:4.3.5-0+deb11u1+rpt3).
The following package was automatically installed and is no longer required:
  raspinfo
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing 'crowsnest' Dependencies ... [OK]
Linking crowsnest ... [OK]
Found existing 'crowsnest.conf' in /home/iain/printer_data/config
Checking log_path ...
Setup new log_path: /home/iain/printer_data/logs
Build dependend Stream Apps ...
Cloning ustreamer repository ...
Cloning into 'bin/ustreamer'...
remote: Enumerating objects: 8990, done.
remote: Counting objects: 100% (512/512), done.
remote: Compressing objects: 100% (251/251), done.
remote: Total 8990 (delta 267), reused 458 (delta 245), pack-reused 8478
Receiving objects: 100% (8990/8990), 5.42 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (6004/6004), done.
INFO: ustreamer found.
make ustreamer-bin
make[1]: Entering directory '/home/iain/crowsnest/bin'
make[1]: warning: -j4 forced in makefile: resetting jobserver mode.
Compiling ustreamer with OMX Support.
Changening to commit '61ab2a8' 
WITH_OMX=1 make -C ustreamer
make[2]: Entering directory '/home/iain/crowsnest/bin/ustreamer'
make apps
make[3]: Entering directory '/home/iain/crowsnest/bin/ustreamer'
make -C src
make[4]: Entering directory '/home/iain/crowsnest/bin/ustreamer/src'
-- CC libs/base64.c
-- CC libs/frame.c
-- CC libs/logging.c
-- CC libs/memsink.c
-- CC libs/options.c
-- CC libs/unjpeg.c
-- CC ustreamer/blank.c
-- CC ustreamer/data/blank_jpeg.c
-- CC ustreamer/data/index_html.c
-- CC ustreamer/device.c
-- CC ustreamer/encoder.c
-- CC ustreamer/encoders/cpu/encoder.c
-- CC ustreamer/encoders/hw/encoder.c
-- CC ustreamer/http/bev.c
-- CC ustreamer/http/mime.c
-- CC ustreamer/http/path.c
-- CC ustreamer/http/server.c
-- CC ustreamer/http/static.c
-- CC ustreamer/http/unix.c
-- CC ustreamer/http/uri.c
-- CC ustreamer/main.c
-- CC ustreamer/options.c
-- CC ustreamer/stream.c
-- CC ustreamer/workers.c
-- CC ustreamer/encoders/omx/component.c
-- CC ustreamer/encoders/omx/encoder.c
-- CC ustreamer/encoders/omx/formatters.c
-- CC ustreamer/encoders/omx/vcos.c
-- CC ustreamer/h264/encoder.c
-- CC ustreamer/h264/stream.c
-- CC dump/file.c
ustreamer/h264/encoder.c: In function ‘_h264_encoder_compress_raw’:
ustreamer/h264/encoder.c:326:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  326 |     in->data = (uint8_t *)vcsm_vc_hdl_from_hdl(src_vcsm_handle);
      |                ^
-- CC dump/main.c
== LD ustreamer-dump.bin
== LD ustreamer.bin
/usr/bin/ld: skipping incompatible /opt/vc/lib/libbcm_host.so when searching for -lbcm_host
/usr/bin/ld: skipping incompatible /opt/vc/lib/libvcos.so when searching for -lvcos
/usr/bin/ld: skipping incompatible /opt/vc/lib/libvcsm.so when searching for -lvcsm
/usr/bin/ld: cannot find -lvcsm
/usr/bin/ld: skipping incompatible /opt/vc/lib/libvcsm.so when searching for -lvcsm
/usr/bin/ld: skipping incompatible /opt/vc/lib/libopenmaxil.so when searching for -lopenmaxil
/usr/bin/ld: cannot find -lopenmaxil
/usr/bin/ld: skipping incompatible /opt/vc/lib/libopenmaxil.so when searching for -lopenmaxil
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal.so when searching for -lmmal
/usr/bin/ld: cannot find -lmmal
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal.so when searching for -lmmal
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_core.so when searching for -lmmal_core
/usr/bin/ld: cannot find -lmmal_core
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_core.so when searching for -lmmal_core
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_util.so when searching for -lmmal_util
/usr/bin/ld: cannot find -lmmal_util
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_util.so when searching for -lmmal_util
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_vc_client.so when searching for -lmmal_vc_client
/usr/bin/ld: cannot find -lmmal_vc_client
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_vc_client.so when searching for -lmmal_vc_client
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_components.so when searching for -lmmal_components
/usr/bin/ld: cannot find -lmmal_components
/usr/bin/ld: skipping incompatible /opt/vc/lib/libmmal_components.so when searching for -lmmal_components
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:101: ustreamer.bin] Error 1
make[4]: Leaving directory '/home/iain/crowsnest/bin/ustreamer/src'
make[3]: *** [Makefile:38: apps] Error 2
make[3]: Leaving directory '/home/iain/crowsnest/bin/ustreamer'
make[2]: *** [Makefile:28: all] Error 2
make[2]: Leaving directory '/home/iain/crowsnest/bin/ustreamer'
make[1]: *** [Makefile:52: ustreamer-bin] Error 2
make[1]: Leaving directory '/home/iain/crowsnest/bin'
make: *** [Makefile:42: all] Error 2
make: *** [Makefile:37: install] Error 2
>>>>>> Something went wrong! Please try again...
iain@mainsail:~/kiauh $ 
 

### What did you expect to happen

Should have installed without error

### How to reproduce

Install through kiauh.sh

**Comment by KwadFan** [comment]
Then I think we could close this ;)
