### ISSUE TITLE
Raspicam 

### ISSUE THREAD

**Issue by Michel-lev** [mainsail-crew/crowsnest#126]
### What happened

Good morning
 I updated to the latest version everything went well however I noticed that I have a 15 cm cable it works and when I put a 1 meter cable it does not work new cable hence  comes the problem

### What did you expect to happen

I am waiting for the 1 meter cable to work
### How to reproduce

Just change the 15 cm cable to a 1 meter one

**Comment by Jacques1476** [comment]
Bonjour j'ai le même problème je vais voir avec des cable de 30 cm et 60 cm si le problème est toujours la car le 1 mètre et 1m12 ça ne fonctionne pas que 15 cm

**Comment by meteyou** [comment]
Pls write English or we have to close this issue...

**Comment by KwadFan** [comment]
Hello @Jacques1476 and @Michel-lev,

Just to give you a brief introduction to crowsnest. this is only a bash script started by debian's init system called `systemd`
This bash script only starts one of the available and compatible streamers called ustreamer and camera-streamer, both arent developed by myself and also I didint develop the hardware limitations of a raspberry pi.

So, if you ribbon cable in a certain length isnt working, that is not an crowsnest bug, I cant write better ribbon cables for you.... Please headover to raspberry forum or contact support of the manufacturer.

Also I2C (pronounced I squared C) is a short distance data transmission protocol even in controlled environments and industry quality cables you are limited to an length of 2,25m distance. A printer and a 2 Dollar ribbon cable is neither of that.


Therefor I will close this issue.
