### ISSUE TITLE
Update section error

### ISSUE THREAD

**Issue by justinr54321** [mainsail-crew/crowsnest#129]
### What happened

Had problems updating from v3 to v4, so I uninstalled crowsnet completely and did a clean install to v4. I now have an update issue in the update section of my interface, Fluidd.

### What did you expect to happen

To be able to have the update section work.

### How to reproduce

Did a clean uninstall of v3, removing everything to do with crowsnest, and upgraded to v4 as per https://crowsnest.mainsail.xyz/setup/installation.

I originally installed v3 through kiuah, and uninstalled it through there to before I did the clean install of v4 through the above site.

### Additional information

![image](https://github.com/mainsail-crew/crowsnest/assets/82848637/9f14f987-9bba-4a01-b1df-6901983f29c0)

**Comment by meteyou** [comment]
if you check the version number in fluidd, it also display the old version number. the moonraker update manager is just unsync with your local repo. just refresh it or wait until moonraker recheck it. this state have nothing todo if crowsnest is working or not. its just the "update manager state".
