### ISSUE TITLE
Huge delay (7s) between rendered image and reality

### ISSUE THREAD

**Issue by bistory** [mainsail-crew/crowsnest#13]
### What happened

I used to use ustreamer directly then I switched to crowsnest in order to simplify my configuration.
However I now expect a delay (about 7s) between reality and the rendered image.
I tried stopping webcamd and started ustreamer directly using my own service and that delay disappears...

Do you experience the same thing ?

Here is my configuration : 

```
[webcamd]
log_path: ~/klipper_logs/webcamd.log    # Default logfile in ~/klipper_logs/webcamd.log
log_level: quiet                        # Valid Options are quiet/verbose/debug

[cam 1]
mode: mjpg                              # mjpg/rtsp/webrtc
port: 8080                              # Port
device: /dev/video0                     # See Log for available ...
resolution: 1296x972                    # widthxheight format
max_fps: 15                             # If Hardware Supports this it will be forced, ohterwise ignored/coerced.
custom_flags: --buffers=2 --slowdown   # You can run the Stream Services with custom flags.
```

Thanks for any hint that could help :-)

### What did you expect to happen

A delay of maximum 1s

### How to reproduce

Compare streaming from ustreamer directly and from crowsnest.

**Comment by KwadFan** [comment]
Hi,
So, no I never experienced that.
Could you provide some additional informations please?

What OS did you use?
Are there any Proxys installed?
If yes, did you disable buffering and caching?
Which type of SBC/Pi do you use?
What type of camera do you use?
How many RAM did you configure for the GPU ( Raspberry Pis)?

As a Hint if you use a Raspicam please DONT! override the buffersize of 5, this is essential for ustreamer. Also slowdown, makes especccialy in Mainsail using Adaptive Streamer unwanted behaviors.

Regards

**Comment by KwadFan** [comment]
Forget to append...

Please set log_level: to debug and add in section [webcamd] delete_log: true

Restart webcamd and wait until the behavior comes back, take the log at this point please and attach it also.

**Comment by bistory** [comment]
> Hi, So, no I never experienced that. Could you provide some additional informations please?
> 
> What OS did you use? Are there any Proxys installed? If yes, did you disable buffering and caching? Which type of SBC/Pi do you use? What type of camera do you use? How many RAM did you configure for the GPU ( Raspberry Pis)?
> 
> As a Hint if you use a Raspicam please DONT! override the buffersize of 5, this is essential for ustreamer. Also slowdown, makes especccialy in Mainsail using Adaptive Streamer unwanted behaviors.
> 
> Regards

Ok it seems that ditching buffers and slowdown options did the trick !
Strange as it never made problems with ustreamer !

I will keep an eye on this issue just in case it reappears soon :-)
For reference, I'm using a headless Rpi 4 with 128Mo of RAM for video, running on RaspiOS, with a cheap Rpi camera
It runs locally on my network without proxy of any kind, the Pi is connected to the WiFi at the moment (will change that in the future)
