### ISSUE TITLE
Webkamera streaming missing after update

### ISSUE THREAD

**Issue by DVSVIDEO** [mainsail-crew/crowsnest#133]
### What happened

I haven't updated anything under mainsail for a couple of weeks. Yesterday I updated everything in the machine menu with update manager using update all componenets.
After rebooting there was no camera video stream.
On Github many people complained about this bug, but the comments were closed. Discord is too complicated for me.
Please help me.
(Once it will work I will not update it anymore, because after the artificial monthly update the connection to the base page of raspberry was lost.
It took me 3 days until a method found in a reddit post (USB port renaming) solved it)

### What did you expect to happen

I expected it to be better, but it got worse...

### How to reproduce

I cannot restore, there is currently no webcam video

**Comment by meteyou** [comment]
Pls read the guide... https://github.com/mainsail-crew/crowsnest/issues/120
