### ISSUE TITLE
Incorrect repository paths in documentation

### ISSUE THREAD

**Issue by twelho** [mainsail-crew/crowsnest#134]
### What happened

On any of the documentation pages on https://crowsnest.mainsail.xyz/, when clicking the three dots and then selecting "Edit on GitHub", one is redirected to https://github.com/mainsail-crew/gb-crowsnest/, which doesn't exist. In fact, the paths seem to be a bit all over the place, for example the "Installation" page links to https://github.com/mainsail-crew/gb-crowsnest/blob/main/setup/installation/README.md, which has no equivalent in this repo (nor https://github.com/mainsail-crew/gb-docs, nor https://github.com/mainsail-crew/docs). 

### What did you expect to happen

Clicking on "Edit on GitHub" brings the user to the correct documentation file in GitHub.

### How to reproduce

On any of the documentation pages on https://crowsnest.mainsail.xyz/, click the three dots and then select "Edit on GitHub".

### Additional information

How and from where is the Crowsnest documentation built? I tried searching for `gb-crowsnest` across all the mentioned repos, but found no hits.

**Comment by meteyou** [comment]
The repo was private. I forgot it to change the visibility when we go live with the new docs. Now the lik should work. Thx for the report!
