### ISSUE TITLE
Installation fails if using "bullseye" Image

### ISSUE THREAD

**Issue by KwadFan** [mainsail-crew/crowsnest#15]
### What happened

Due missing dependency 'libjpeg8-dev' in bullseye images, the Installer fails.

### What did you expect to happen

Well, a running install and a successful install of crowsnest :)

### How to reproduce

Get Raspberry Pi OS latest Image, clone crowsnest and run 'make install'

### Additional information

As workaround for now use 'libjpeg9-dev' or 'libjpeg62-turbo-dev'
After that run 'make build'

**Comment by tonyshackelton** [comment]
Hi there, I can't get this built with libjpegturbo-dev, and libjpeg9-dev is another dead pointer to libturbo62-dev just like 8 is, which is installed installed but still fails. What's the workaround?

--Current PIOS bulleye, system context--
Package libjpeg9-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev:armhf libjpeg62-turbo-dev

libjpeg62-turbo-dev is already the newest version (1:2.0.6-4).

--err from make install--
Installing 'ustreamer' Dependencies ...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Package 'libjpeg8-dev' has no installation candidate
ERROR: Error 100 occured on line 270
ERROR: Stopping install.sh.
Goodbye...
make: *** [Makefile:36: install] Error 1

**Comment by KwadFan** [comment]
Close due 6071c6f
