### ISSUE TITLE
After installing Crowsnest, camera is not working anymore

### ISSUE THREAD

**Issue by Regulate3772** [mainsail-crew/crowsnest#161]
### What happened

I use the following devices:
- Raspberry Pi Camera 1.3 
- Raspberry Pi 3b
- Sovol SV06 Plus (not relevant here)

And software:
- Raspberry OS lite and full both tested
Via Kiauh:
- Klipper
- Moonraker
- Mainsail
- Crowsnest 

Issue: Webcam does not work with Crowsnest / Mainsail
The webcam works perfectly fine with Octoprint (just tested again) but not with Mainsail.

Looking in the crowsnest.log I find the message: 
[08/04/23 13:35:54] crowsnest: INFO: Detect available Devices
[08/04/23 13:35:54] crowsnest: ERROR: No usable Devices Found. Stopping crowsnest.

Further tests:
I tried to reinstall the software a couple of times with different OS and made an interesting finding:
After installing Rasberry OS, the webcam does work. I can find it via SSH with the command
`libcamera-still --list-cameras`

Same after individually installing and testing: Klipper, Moonraker and Mainsail. The command does find the camera.

But after installing Crowsnest, I get the message "No cameras available!"

So that makes me think that Crowsnest does something to libcamera or the OS and the webcam is not working anymore at all, not just in Mainsail/OS.

I also tried to reinstall libcamera but no luck. The only way to get it working again is to format the SD Card and reinstall the OS.

### What did you expect to happen

Webcam working in Mainsail

### How to reproduce

Installing Crowsnest: Camera is not working anymore.

**Comment by meteyou** [comment]
https://crowsnest.mainsail.xyz/faq/how-to-setup-a-raspicam
