### ISSUE TITLE
white screen after update

### ISSUE THREAD

**Issue by Fuckingnameless** [mainsail-crew/crowsnest#162]
### What happened

error during installation:

Cloning camera-streamer repository ...
fatal: The empty string is not a valid path
make: *** [Makefile:17: install] Error 128

### What did you expect to happen

install v4 normally

### How to reproduce

remove/install via terminal or update through the web interface

### Additional information

[crowsnest (1).log](https://github.com/mainsail-crew/crowsnest/files/12269574/crowsnest.1.log)

**Comment by mryel00** [comment]
With this information it's hard to say what exactly is going on at your setup right now. As you are talking about `remove/install` or `updating`. These are all different things and that might lead to the strange setup you right now have.
I would recommend trying to run `cd ~/crowsnest && make uninstall`. Then remove the crowsnest directory and follow the installation instructions again: https://crowsnest.mainsail.xyz/setup/installation
If you need further help, please join our [discord server](https://discord.gg/mainsail) and open a post in support-forum.
