### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Outofbox11** [mainsail-crew/crowsnest#165]
### What happened

using putty to ssd in or install using kiauh, it all end with failed install.

/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/

###### Cloning 'crowsnest' repository ...
Cloning into '/home/pi/crowsnest'...
remote: Enumerating objects: 1453, done.
remote: Counting objects: 100% (434/434), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 1453 (delta 367), reused 338 (delta 318), pack-reused 1019
Receiving objects: 100% (1453/1453), 567.59 KiB | 2.17 MiB/s, done.
Resolving deltas: 100% (883/883), done.

###### Checking for the following dependencies:
● git
● make
[✓ OK] Dependencies already met!
Installer will prompt you for sudo password!

###### Launching crowsnest installer ...
crowsnest - A webcam daemon for multiple Cams and stream services.

        Ahoi!
        Thank you for installing crowsnest ;)
        This will take a while ...
        Please reboot after installation has finished.

Running apt-get update first ...

Get:1 http://security.debian.org/debian-security testing-security InRelease [48.0 kB]
Get:2 http://deb.debian.org/debian testing InRelease [168 kB]
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Err:1 http://security.debian.org/debian-security testing-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
Err:2 http://deb.debian.org/debian testing InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Get:5 http://deb.debian.org/debian testing-updates InRelease [49.6 kB]
Err:5 http://deb.debian.org/debian testing-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Reading package lists...
W: GPG error: http://security.debian.org/debian-security testing-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
E: The repository 'http://security.debian.org/debian-security testing-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian testing InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian testing-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian testing-updates InRelease' is not signed.
Running apt-get update first ... [FAILED]
Something went wrong!
Please copy the last output and head over to

        https://discord.gg/mainsail

open a ticket in #supportforum ...
make: *** [Makefile:17: install] Error 1
>>>>>> Something went wrong! Please try again...

### What did you expect to happen

finish installation

### How to reproduce

every time I tried to install

**Comment by mryel00** [comment]
This isn't a bug with crowsnest. This is an overall system problem. The same problem would come with just running `sudo apt update`.
You can try to run `sudo apt install --reinstall debian-keyring`, maybe this will fix it.
If it doesn't fix the problem. Please join our [discord](https://discord.gg/mainsail) and open a post in the support-forum or make your own research to educate yourself on this error.
