### ISSUE TITLE
libcamera.so.0.0.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kaelum** [mainsail-crew/crowsnest#166]
### What happened

The latest update broke my Nozzle CAM.

### What did you expect to happen

It should work.

### How to reproduce

Updated from a previous version.

**Comment by Kaelum** [comment]
Doing the following, fixed the issue after a restart:

```
cd ~/crowsnest
make buildclean
make build
```

**Comment by mryel00** [comment]
Sry for the late reply, I somehow forgot to answer this issue.
You only need to rebuild camera-streamer, as this is a problem with building it manually, so nothing we can do about it directly atm.
The commands would be:
```bash
cd ~/crowsnest/bin/camera-streamer
make clean
make
```
If the `make` command fails for someone, try to use `make -j2` or `make -j1`.

**Comment by othbert** [comment]
Also needed to do this on a fresh mainsailos image today. Thanks for the report and the fix!
