### ISSUE TITLE
Camera disconnects after few seconds

### ISSUE THREAD

**Issue by Saikedo** [mainsail-crew/crowsnest#167]
### What happened

I am experiencing an issue where the camera freezes and disconnects after few seconds.

NOTE: It seems like I can get a relatively more stable operation when I am using `ustreamer` instead of `camera-streamer`

### What did you expect to happen

Expect the camera to continue working.

### How to reproduce

It seems like it works fine for some time after total printer shutdown and restart.

The issue starts happening randomly it seems at some points. After the camera freezes, restarting crowsnest always results in the same behaviour where it connects for a brief moment, then freezes again.

### Additional information

I am using a 3DO nozzle cam which is connected to the Raspberry Pi 4B (8GB) via USB.

Here are the Crowsnest Logs and the content of the config file.

[crowsnest.log](https://github.com/mainsail-crew/crowsnest/files/12345175/crowsnest.log)

<img width="283" alt="image" src="https://github.com/mainsail-crew/crowsnest/assets/19657054/25f061f7-2610-4465-bc46-7f44b0e4e830">

<img width="324" alt="image" src="https://github.com/mainsail-crew/crowsnest/assets/19657054/ea89ad63-a51a-4b15-932c-eb2d6e74ef49">

**Comment by mryel00** [comment]
Please join the [Discord](https://discord.gg/mainsail) to debug your issue
