### ISSUE TITLE
Unable to Build or Recompile: make: *** [Makefile:23: build] Error 2

### ISSUE THREAD

**Issue by Imburr** [mainsail-crew/crowsnest#168]
### What happened

I updated system, Klipper, and Crowsnest. Klipper came back dirty, so I had to hard recover. Afterwards, I obviously had to reinstall all of my things- KAMP, ERCF, Timelapse, and Crowsnest. I have installed, cleaned, and recompiled to no avail. 

### What did you expect to happen

I expected Crowsnest to reinstall.

### How to reproduce

This:
make buildclean
make build

Or this:

cd ~
git clone https://github.com/mainsail-crew/crowsnest.git
cd ~/crowsnest
sudo make install

### Additional information

`/usr/bin/ld: warning: libssh-gcrypt.so.4, needed by /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_closedir@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_options_set@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_free@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_rename@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_dir_eof@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_close@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_connect@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_new@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_unlink@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_opendir@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_options_parse_config@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_get_error@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_init@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_tell64@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_userauth_password@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_seek64@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_open@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_new@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_read@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_attributes_free@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_stat@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_try_publickey_from_file@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_get_error@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_write@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_free@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_rmdir@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_fstat@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_userauth_pubkey@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_userauth_list@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_userauth_autopubkey@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `sftp_readdir@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `privatekey_from_file@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_userauth_none@LIBSSH_4_5_0'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libavformat.so: undefined reference to `ssh_disconnect@LIBSSH_4_5_0'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:77: camera-streamer] Error 1
rm device/buffer_lock.o device/v4l2/buffer.o output/http_hls.o device/camera/camera_output.o html/webrtc.html.c device/v4l2/buffer_list.o html/webrtc.html.o device/buffer_queue.o util/ffmpeg/remuxer.o device/buffer.o device/camera/camera_decoder.o device/links.o output/webrtc/webrtc.o cmd/list-devices/main.o device/v4l2/debug.o device/camera/camera_input.o util/opts/opts.o device/libcamera/device.o device/v4l2/device_options.o output/http_ffmpeg.o device/camera/camera.o device/camera/camera_rescaller.o device/libcamera/fake_camera.o output/rtsp/rtsp.o cmd/camera-streamer/main.o device/buffer_list.o device/camera/camera_debug.o util/http/http.o device/camera/camera_pipeline.o device/dummy/buffer_list.o util/opts/control.o output/http_jpeg.o cmd/camera-streamer/opts.o util/opts/fourcc.o output/output.o device/v4l2/device_list.o device/device_list.o device/v4l2/device_media.o device/dummy/device.o device/libcamera/buffer_list.o device/dummy/dummy.o device/libcamera/libcamera.o util/http/http_methods.o cmd/camera-streamer/status.o device/dummy/buffer.o cmd/camera-streamer/http.o util/opts/log.o html/index.html.o html/index.html.c device/camera/camera_isp.o device/v4l2/v4l2.o device/device.o device/v4l2/device.o device/libcamera/buffer.o output/http_h264.o
make[2]: Leaving directory '/home/pi/crowsnest/bin/camera-streamer'
make[1]: *** [Makefile:62: all] Error 2
make[1]: Leaving directory '/home/pi/crowsnest/bin/camera-streamer'
make: *** [Makefile:23: build] Error 2
pi@mainsailos:~/crowsnest $`

**Comment by mryel00** [comment]
> Afterwards, I obviously had to reinstall all of my things- KAMP, ERCF, Timelapse, and Crowsnest. I have installed, cleaned, and recompiled to no avail.

You shouldn't have to reinstall those things after a hard recover of klipper. A hard recovery will reset the klipper repository inside the klipper directory, but all those things mentioned of you aren't inside the klipper directory. So there was another overall problem, or you made something different.

To the code you sent. There are triple quote code blocks, that would format that error a lot better. Use ` three times before and after the error on new lines.

And even if it's sometimes hard for us to do so, but I have to sent you over to the [discord](https://discord.gg/mainsail) that you open a post inside the support-forum. As this error isn't something about crowsnest directly, but the build process of [camera-streamer](https://github.com/ayufan/camera-streamer), it will be easier for us to troubleshoot it there.
