### ISSUE TITLE
Stream audio for webcams with built in microphone

### ISSUE THREAD

**Issue by willuhmjs** [mainsail-crew/crowsnest#171]
### Is your feature request related to a problem? Please describe

I would like to hear any abnormalities in my print via the microphone in my webcam. 

### Describe the solution you'd like

Allow user to choose the audio input device to broadcast to the front end.

### Describe alternatives you've considered

I tried messing with ffmpeg but it would be easier to have it built into the software.

**Comment by mryel00** [comment]
There are multiple things making this not suitable for crowsnest.
As crowsnest is just a wrapper for streaming backends (ustreamer and camera-streamer), you would have to ask them to implement such a thing. For ustreamer I found [this](https://github.com/pikvm/ustreamer/issues/122) and for camera-streamer [this](https://github.com/ayufan/camera-streamer/issues/40). So both backends don't support audio streaming.
As ustreamer is currently only available for mjpg streams in crowsnest, there wouldn't even be a possibility to integrate audio into that afaik, as those are just a series of jpg files.
For camera-streamer we got webrtc and rtsp, as those get encoded properly there would be a possibility to add audio, but as you can read in the linked issue above, it's not planned atm.

So this wouldn't suit into crowsnest directly, as crowsnest is just a wrapper to call streaming backends easily.
