### ISSUE TITLE
160MB GPU RAM cause RPI Zero 2 to hang

### ISSUE THREAD

**Issue by Benik3** [mainsail-crew/crowsnest#175]
### What happened

The installation script sets GPU memory to 160MB, which cause RPi Zero 2W to hang during boot.
128MB is OK.

### What did you expect to happen

Boot RPi Zero 2 properly

### How to reproduce

fetch latest master
sudo make install
reboot

**Comment by mryel00** [comment]
Nice catch, I didn't yet had such a problem and I already installed it quite a few times on the pi zero 2w. But you are right and this is a bug inside the code. To be precise it's [here](https://github.com/mainsail-crew/crowsnest/blob/master/tools/libs/set_gpumem.sh#L26-L47) and comes from not using `else if`.

I updated the title as you reported it with a pi zero 2 and we don't recommend to use crowsnest on a pi zero 1.
