### ISSUE TITLE
V4L2 focus_absolute resets to 192 after "Starting ustreamer with Device /dev/video0"

### ISSUE THREAD

**Issue by sleewok** [mainsail-crew/crowsnest#185]
### What happened

I have my V4L2 Control: Options: focus_auto=0,focus_absolute=260,sharpness=4,power_line_frequency=2

When restarting the service I spam the command: v4l2-ctl -d /dev/video0 --list-ctrls-menus

I can see the focus_absolute set to 260 as soon as the log shows: :V4L2 Control: Options: focus_auto=0,focus_absolute=260,sharpness=4,power_line_frequency=2:

Then when it gets to "Starting ustreamer with Device /dev/video0 ..." the value is set to 192. 

The default value is 0 and I have no idea where 192 is coming from.

### What did you expect to happen

I expect my focus_absolute to set to the value specified in the config file.

### How to reproduce

Set the value in my config and restart the service.

### Additional information

Is there anywhere else the 192 value could be set that is overriding this?

**Comment by mryel00** [comment]
Sry that it took so long to respond here. The only thing I could think of right now, without any log, would be that you maybe have some kind of error inside your config or just edit the wrong config file.
We support such things on [Discord](https://discord.gg/mainsail), so please join it and open a post inside the support-forum for further troubleshooting/help.
