### ISSUE TITLE
[Makefile:37: install] Error 128

### ISSUE THREAD

**Issue by SimpleRed06** [mainsail-crew/crowsnest#193]
### What happened

I was installing Crowsnest on my elegoo neptune 4 pro with stock emmc and then I got the following error: fatal: 
could not create work tree dir 'bin/ustreamer': Permission denied
make: *** [Makefile:37: install] Error 128

The full log of the installation:

crowsnest - A webcam daemon for multiple Cams and stream services.

        Ahoi!
        Thank you for installing crowsnest ;)
        This will take a while ...
        Please reboot after installation has finished.

Running apt update first ...
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://deb.debian.org/debian buster-backports InRelease
Hit:4 http://security.debian.org buster/updates InRelease
Hit:5 http://fi.mirror.armbian.de/apt buster InRelease
Reading package lists...
Installing 'crowsnest' Dependencies ...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.6).
crudini is already the newest version (0.7-1).
findutils is already the newest version (4.6.0+git+20190209-2).
libbsd-dev is already the newest version (0.9.1-2+deb10u1).
libevent-dev is already the newest version (2.1.8-stable-4).
libjpeg-dev is already the newest version (1:1.5.2-2+deb10u1).
libxcomposite1 is already the newest version (1:0.4.4-2).
libxtst6 is already the newest version (2:1.2.3-1).
bsdutils is already the newest version (1:2.33.1-0.1).
v4l-utils is already the newest version (1.16.3-3).
curl is already the newest version (7.64.0-4+deb10u7).
ffmpeg is already the newest version (7:4.1.11-0+deb10u1).
git is already the newest version (1:2.20.1-2+deb10u8).
0 upgraded, 0 newly installed, 0 to remove and 223 not upgraded.
Installing 'crowsnest' Dependencies ... [OK]
Linking crowsnest ... [OK]
Found existing 'crowsnest.conf' in /home/mks/printer_data/config
Checking log_path ...
Setup new log_path: /home/mks/printer_data/logs
Build dependend Stream Apps ...
Cloning ustreamer repository ...
fatal: could not create work tree dir 'bin/ustreamer': Permission denied
make: *** [Makefile:37: install] Error 128

### What did you expect to happen

I thought it would install normally.

### How to reproduce

Follow the exact steps in the installation manual.

**Comment by mryel00** [comment]
Please join our [Discord](https://discord.gg/mainsail) for debugging this issue.
This seems like you messed up at some point during the first steps.
