### ISSUE TITLE
Permission denied moonraker.conf

### ISSUE THREAD

**Issue by Lino77** [mainsail-crew/crowsnest#2]
Adding update manager to moonraker.conf
grep:  : No such file or directory
./installer_ms050.sh: line 108: /home/pi/klipper_config/moonraker.conf: Permission denied

**Comment by KwadFan** [comment]
Hey Lino77, sorry for my very delayed answer... My mainjob is keeping me busy so close to christmas.
Thank you for your report, I hope I get the new Installer done tomorrow.
Stay tuned ...
