### ISSUE TITLE
No video stream even though everything appears correct in Crowsnest

### ISSUE THREAD

**Issue by JYCrois** [mainsail-crew/crowsnest#228]
### What happened

I have just finished installing the official versions on a Flsun SpeederPad following Guilouz's tutorial, everything works correctly I only have one problem, my camera does not work, it works very well before installing the official versions but now under crowsnest nothing to do, yet I have no errors everything is up to date (see PJ), any idea? if there really is no solution for crowsnest is it possible to reinstall MPG-Streamer and how (I didn't see the option in KIAUH)? cordially thanking you for your work,
### What did you expect to happen

be able to have my camera functional with crowdnest
![Crowsnest conf](https://github.com/mainsail-crew/crowsnest/assets/116349530/9c6f9058-8ebd-483b-9673-e58af93a9afd)
![Gestionnaire de mise à jour](https://github.com/mainsail-crew/crowsnest/assets/116349530/927506dd-9c1f-44e2-acfb-4ead5a40dfdd)
![moonraker conf](https://github.com/mainsail-crew/crowsnest/assets/116349530/82a20b9b-9461-476a-b64f-8b9880be8ffd)
![réglage caméra](https://github.com/mainsail-crew/crowsnest/assets/116349530/1660f1fc-b618-4725-8873-506b4257401b)

### How to reproduce

.

### Additional information

.

**Comment by mryel00** [comment]
Sry, but I don't speak french. So please edit your issue and translate it in english.

**Comment by mryel00** [comment]
Ok, thank you, now I can read it, but it seems like you want support, so please join our [Discord](https://discord.gg/mainsail) and open a post inside the support-forum or open a post in our [GitHub Discussions](https://github.com/orgs/mainsail-crew/discussions/categories/help). In both cases you should post some logs.

> is it possible to reinstall MPG-Streamer

We don't provide any installation instructions for this, you have to do your own research on that. But this software is outdated by years. Also it should only be uninstalled when you have uninstalled it with KIAUH. Crowsnest only disables the service.

Overall FLSUN Speederpads work with Crowsnest, as you can see in e.g. this issue #117
