### ISSUE TITLE
Raspberry Pi Cam not connecting

### ISSUE THREAD

**Issue by rafaelmontserrat** [mainsail-crew/crowsnest#233]
### What happened

I have a RPI 4, with a RPI cam v2.1. I have followed all the possible instructions and troubleshooting documentation but still cant get the camera image to show up on mainsail.

### What did you expect to happen

The camera to work.

### How to reproduce

My cam is connected to my PI in the camera slot with the ribbon cable. My config is the following:

[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: verbose                      # Valid Options are quiet/verbose/debug
delete_log: false                       # Deletes log on every restart, if set to true
no_proxy: false

[cam 1]
mode: camera-streamer                   # ustreamer - Provides mjpg and snapshots. (All devices)
                                        # camera-streamer - Provides webrtc, mjpg and snapshots. (rpi + Raspi OS based only)
enable_rtsp: false                      # If camera-streamer is used, this enables also usage of an rtsp server
rtsp_port: 8554                         # Set different ports for each device!
port: 8080                              # HTTP/MJPG Stream/Snapshot Port
device: /base/soc/i2c0mux/i2c@1/imx219@10   # See Log for available ...
resolution: 1280x720                    # widthxheight format
max_fps: 15                             # If Hardware Supports this it will be forced, otherwise ignored/coerced.
#custom_flags:                          # You can run the Stream Services with custom flags.
#v4l2ctl:                               # Add v4l2-ctl parameters to setup your camera, see Log what your cam is capable of.

The device section I got it from my log file on mainsail. When I go to add camera, I dont get image on any of the options.

### Additional information

I have enabled the camera support in raspi-config.
I have used this pi and camera in the past and it was plug and play, but changed my setup recently and it is not anymore.

Here all the resources I have followed to try and troubleshoot it myself:
https://crowsnest.mainsail.xyz/configuration/cam-section
https://github.com/mainsail-crew/crowsnest/blob/master/resources/crowsnest.conf
https://github.com/mainsail-crew/crowsnest/issues/143#issuecomment-1646048785
https://github.com/mainsail-crew/crowsnest/issues/151
https://crowsnest.mainsail.xyz/faq/how-to-setup-a-raspicam

Appreciate any help.

**Comment by mryel00** [comment]
As follow up because the bot isn't updated yet.
You can also use the [mainsail-crew GitHub Discussions](https://github.com/orgs/mainsail-crew/discussions)
