### ISSUE TITLE
Crowsnest install errors and ustreamer fails to install

### ISSUE THREAD

**Issue by IdahoCreator** [mainsail-crew/crowsnest#247]
### What happened

Durring install of crowsnest I get the following error messages and stops install.

From https://github.com/sctplab/usrsctp
 * branch            7c31bd35c79ba67084ce029511193a19ceb97447 -> FETCH_HEAD
Submodule path 'third_party/libdatachannel/deps/usrsctp': checked out '7c31bd35c79ba67084ce029511193a19ceb97447'
Build 'ustreamer' using 2 Cores ...
make apps
make[1]: Entering directory '/home/klipper/crowsnest/bin/ustreamer'
make -C src
make[2]: Entering directory '/home/klipper/crowsnest/bin/ustreamer/src'
-- CC libs/base64.c
-- CC libs/device.c
-- CC libs/frame.c
libs/device.c: In function '_device_open_dv_timings':
libs/device.c:637:2: error: a label can only be part of a statement and a declaration is not a statement
  637 |  struct v4l2_event_subscription sub = {.type = V4L2_EVENT_SOURCE_CHANGE};
      |  ^~~~~~
make[2]: *** [Makefile:125: build/libs/device.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/klipper/crowsnest/bin/ustreamer/src'
make[1]: *** [Makefile:38: apps] Error 2
make[1]: Leaving directory '/home/klipper/crowsnest/bin/ustreamer'
make: *** [Makefile:28: all] Error 2
make: *** [Makefile:19: install] Error 2

### What did you expect to happen

I expected the install to complete normally.

### How to reproduce

Happens everytime I run isntall

### Additional information

I am doing a clean install from Kiauh with crowsnest failing and by installing just crowsnest via github clone and following instructions from github post.

**Comment by mryel00** [comment]
The error is during ustreamer compiling. I'm already working on a solution. Here is a workaround:
```sh
cd crowsnest
make config
```Use all the default values (just hit `enter` a few times)

```sh
nano tools/.config
```Change the third line from
```
CROWSNEST_USTREAMER_REPO_BRANCH="master"
```to```
CROWSNEST_USTREAMER_REPO_BRANCH="v5.57"
```Then hit `ctrl+s` and `ctrl+x` to save and exit.

Try again to install it:
```sh
cd ~/crowsnest
sudo make install
```
