### ISSUE TITLE
Sudo Make Install not working

### ISSUE THREAD

**Issue by MadCatUSA** [mainsail-crew/crowsnest#248]
### What happened

Attempting to run sudo make install to correct the "ustreamer not found" error, and make install is not working.

### What did you expect to happen

Re-installation of Crow's Nest.

### How to reproduce

Run sudo make install from the ~/crowsnest directory

### Additional information

![image](https://github.com/mainsail-crew/crowsnest/assets/95143840/9e33ded9-e41b-4ada-b6b4-3c883c95782e)

**Comment by mryel00** [comment]
Duplicate #247
