### ISSUE TITLE
Klipperscreen hdmi display DPMS stops working when crowsnest is installed and USB camera attached.

### ISSUE THREAD

**Issue by ajaytanna** [mainsail-crew/crowsnest#259]
### What happened

On two completely different installs - Voron 2.4 with Manta M8P and CB1 and the other Creality ender 3 S1 pro with Raspberry pi 4B - both running Klipper with Klipperscreen. Whenever  a USB camera is used with crowsnest streaming it works but breaks the klipperscreen display DPMS, and does not turn the screen off after the set standby duration. Removing crowsnest or disconnecting the USB camera restores the DPMS functionality. I have to use mjpeg streamer wihch works fine with DPMS

### What did you expect to happen

DPMS should work by kicking off monitor power saving

### How to reproduce

Install as stated above

### Additional information

None

**Comment by mryel00** [comment]
Crowsnest is only starting backends for you, so it shouldn't interfere with anything. So this bug has something to do with ustreamer, camera-streamer or maybe even klipperscreen doing some weird things.
We don't know anything about your configuration or similar, so please go to one of our support possibilities and give us your log.
