### ISSUE TITLE
OSD (On Screen Display)

### ISSUE THREAD

**Issue by Matszwe02** [mainsail-crew/crowsnest#274]
### Is your feature request related to a problem? Please describe

sometimes camera gets stuck and frontend won't detect it

### Describe the solution you'd like

Add an optional overlay to the camera with print status (maybe configurable by user in [cam]?) with print progress, current time, file being printed, etc. like these texts on IP cameras

**Comment by mryel00** [comment]
There are two things mixed up. First you write
> sometimes camera gets stuck and frontend won't detect it

This reads as some issue.
After that you ask some FR:
> Add an optional overlay to the camera with print status

Those are two completey different topics.

For the first one, you should join our [Discord](https://discord.gg/mainsail) or our [Discussions](https://github.com/orgs/mainsail-crew/discussions).

The FR already came up multiple times and is nothing you can do with Crowsnest. Also see #71, #171 and #239. They are all not exacctly what you want, but have basically the same reasoning, to why it won't work in Crowsnest.
