### ISSUE TITLE
Very dark stream with thick green line on the bottom of image when using camera-streamer

### ISSUE THREAD

**Issue by NokkOnEffect** [mainsail-crew/crowsnest#279]
### What happened

When using camera-streamer with my 3DO enclosure cam connected to my Pi 4 1GB running Pi OS Lite 64 Bit, a thick green bar appears on the bottom of the image. The image is also noticably darker.

![camera-streamer WebRTC](https://github.com/user-attachments/assets/24e70689-5eb4-4ee1-928c-fe7a3d7ef359)

The used config is the following:
```None
[cam Enclosure]
mode: camera-streamer
enable_rtsp: true
rtsp_port: 8554
port: 8080
device: /dev/video0
resolution: 1920x1080
max_fps: 30
```

### What did you expect to happen

The line should not be there and the brightness should be roughly equal. like in the picture using ustreamer below.
![ustreamer](https://github.com/user-attachments/assets/4f0a67e3-e5f7-478e-be66-7791a5f4bddb)

The used config is the following:
```None
[cam Enclosure]
mode:  ustreamer
port: 8080
device: /dev/video0
resolution: 1920x1080
max_fps: 30
```

### How to reproduce

Hardware: Pi 4 1GB
OS: Raspberry Pi OS Lite Bookworm 64 Bit
VRAM expanded to 160
3DO nozzle or enclosure cam
Use the configs given above

**Comment by mryel00** [comment]
That's nothing crowsnest can change. Please open an issue in the camera-streamer repo. It's a bug with camera-streamer and the pi hw encoders.
