### ISSUE TITLE
BTT Manta M5P + CB1

### ISSUE THREAD

**Issue by AntoszHUN** [mainsail-crew/crowsnest#283]
### What happened

I downloaded Crowsnest along with MainsailOS. After connecting the camera the FPS is 1. In vain the target is set to 30FPS. Not good. The resolution is all the same, small or big. The FPS value does not change. 

### What did you expect to happen

I was hoping to get 30FPS. 

### How to reproduce

Crowsnest set up camera connected via USB to FPS1. Not difficult to reproduce.

**Comment by mryel00** [comment]
> Crowsnest set up camera connected via USB to FPS1. Not difficult to reproduce.

Working for me like intended, like for other hundreds of users. So no it's not easy to reproduce. It's not a bug, but a question for support
