### ISSUE TITLE
Webcam Stream has low quality after clean start.

### ISSUE THREAD

**Issue by Dreadnouhgt** [mainsail-crew/crowsnest#33]
### What happened

When i start my pi the camera stream is horrible, a restart of crowsnest fixes the issue

Newest Version of Crowsnest. Camera is connected via the raspberry camera port. 

### What did you expect to happen

Camera working properly right from the start. 

### How to reproduce

Seems like im the only one with that error

**Comment by KwadFan** [comment]
Hi,

So, I am now able to reproduce it every time on reboot.
And thanks to lixxbox I might have found a solution.

Please try using
`v4l2ctl: video_bitrate_mode=1,video_bitrate=15000000`
for your raspicam section.

I am already working on a solution to fix that.

**Comment by mhr93** [comment]
hello,
I'm having the same issue running current version:
![image](https://user-images.githubusercontent.com/44025123/202827895-ea941833-c287-4036-b463-02a4c37bdbfa.png)

After raspberry reboot, image looks like this:
![image](https://user-images.githubusercontent.com/44025123/202828045-7cf16cbb-8095-43b4-8907-d31fdbb8b59c.png)
After rebooting crowsnest service:
![image](https://user-images.githubusercontent.com/44025123/202828190-22cbc254-a643-42a0-b7f2-88aa419e2c02.png)

I have check video_bitrate and video_bitrate_mode are set correctly after executing "blockyfix" function, I have tried to add an "sleep" after this step to make sure there is no some kind of time delay when changing configuration, tried to execute the blockyfix some steps before... and I have no clue why it has this behaivour.

I attach here a debug level log with the full trace from start to end of the service starting after rasberry pi reboot and after crowsnest service reboot (I added comments to point each case). Both cases are almost identical
[pi_and_crowsnest_restart.log](https://github.com/mainsail-crew/crowsnest/files/10045830/pi_and_crowsnest_restart.log)

Thanks
