### ISSUE TITLE
Add support for H264 encoding 

### ISSUE THREAD

**Issue by thbl** [mainsail-crew/crowsnest#37]
### Is your feature request related to a problem? Please describe

H264 would make stream more smooth and save bandwidth 

### Describe the solution you'd like

Add support for H264 encoding in mainsail / crownsnest

**Comment by thbl** [comment]
There is even an integration example in the ustream repo :)
https://github.com/pikvm/ustreamer#janus

**Comment by KwadFan** [comment]
Well,

I dont know when it will happen, but I plan to use a new backend in the future.
That will have more then a janus webrtc server ;)

Closing that for now, stay tuned.

**Comment by ph0tic** [comment]
just wanted to show a little love for this request. just realized the used c920 avoided the h.264 purge (maybe?) and really would love a framerate higher than a constant... 2-4fps... even if its just 8, or even 6. or 5.

**Comment by NonaSuomy** [comment]
Does this work now with the new backend?

**Comment by meteyou** [comment]
not really... we tested https://github.com/ayufan/camera-streamer but it doesn't work really stable (mainsail PR for the client: https://github.com/mainsail-crew/mainsail/pull/1275). we also implemented a HLS client for the RTSP mode in crowsnest. this works fine, but it has a really long delay (too long for my taste)

**Comment by NonaSuomy** [comment]
Maybe try using the stuff that PiKVM built. I believe all his stuff is customized for low latency feeds.

**Comment by meteyou** [comment]
@NonaSuomy i tested this one from PiKVM: https://github.com/pikvm/ustreamer/blob/master/docs/h264.md

But it looks like this kills the snapshot URL. We need a solution to have a low-latency stream + snapshots for timelapse.

**Comment by NonaSuomy** [comment]
Can you explain how you tested it? If so then I will set it up the same then ask him for assistance on how to restore a snapshot url as well?

**Comment by NonaSuomy** [comment]
![7AF9A6C3-7AD4-4A63-9AF7-ADC95D3EC1FF](https://user-images.githubusercontent.com/1906575/220061943-854e8951-253b-470b-8375-6fd2f39cd909.png)

**Comment by meteyou** [comment]
I followed the guide from pikvm and then started the webcam with it...
