### ISSUE TITLE
Zooming for webcam views

### ISSUE THREAD

**Issue by Stooovie** [mainsail-crew/crowsnest#44]
### Is your feature request related to a problem? Please describe

I'd love a zoom feature for webcams that have just a little bit too wide angle lens. 

### Describe the solution you'd like

User can specify a zoom level. I don't really care if it actually magnifies the image or just zooms the view canvas.

**Comment by KwadFan** [comment]
Hey @Stooovie ,

As I already answered you on Discord.

> So far if cam supports it via v4l2-ctl it is already, all methods that need software post processing, no. But tbh I think getting better quality and bandwith usage should have priority. Maybe it is possible to do in browser but that is out of my scope.

I think we could close this for now. I will reopen if I find a solution.

Regards Kwad
