### ISSUE TITLE
change target path dir to ~/printer_data/config

### ISSUE THREAD

**Issue by tinymachines3d** [mainsail-crew/crowsnest#45]
### Is your feature request related to a problem? Please describe

With fresh install of Moonraker, klipper_config is no longer used. 

### Describe the solution you'd like

Change
[ -n "$CROWSNEST_DEFAULT_CONF_DIR" ] || CROWSNEST_DEFAULT_CONF_DIR="/home/${BASE_USER}/klipper_config"

To
[ -n "$CROWSNEST_DEFAULT_CONF_DIR" ] || CROWSNEST_DEFAULT_CONF_DIR="/home/${BASE_USER}/printer_data/config"

**Comment by KwadFan** [comment]
Hey, 

This is also related to #41 and #46 
I close this for now please use #46 for further discussions

Regards Kwad
