### ISSUE TITLE
Logitech C920 v4l2-ctl --set-fmt-video

### ISSUE THREAD

**Issue by TomBraun02** [mainsail-crew/crowsnest#57]
### Is your feature request related to a problem? Please describe

V4L2 Control: "--set-ctrl" has already been implemented
I miss the possibility to set the camera to the mode: YUYV with a resolution of 2304x1536 pixel.
I am aware that only 2 images per second are possible, but it is enough for photos.

`v4l2-ctl --set-fmt-video=width=2304,height=1536,pixelformat=0` 
` v4l2-ctl -V` 

Format Video Capture:
        Width/Height      : 2304/1536
        Pixel Format      : 'YUYV' (YUYV 4:2:2)
        Field             : None
        Bytes per Line    : 4608
        Size Image        : 7077888
        Colorspace        : sRGB
        Transfer Function : Rec. 709
        YCbCr/HSV Encoding: ITU-R 601
        Quantization      : Default (maps to Limited Range)

### Describe the solution you'd like

The specification of the parameters set-fmt-video in the config file, like the parameter --set-ctrl

**Comment by KwadFan** [comment]
Well,

Sorry that is not possible as it would force a huge change in the starting process of streamer.
Ustreamer forces MJPEg per default and would need bigger changes in the script that "builds" the parameters for ustreamer.
Using YUYV would also mean that the CPU has to render the Video Stream what would increase the cpu load.

Regard Kwad
