### ISSUE TITLE
README.md example typing error

### ISSUE THREAD

**Issue by Robnex** [mainsail-crew/crowsnest#6]
### What happened

Hello

In your section of ```[cam 1]
streamer: ustreamer
port: 8080
device: /dev/video0
resolution: 640x480
max_fps: 15```
There is the old „streamer“ option instead of the new „mode“.

greetings

### What did you expect to happen

`[cam 1]
mode: mjpeg
port: 8080
device: /dev/video0
resolution: 640x480
max_fps: 15`

### How to reproduce

On uptdating to the new version

**Comment by KwadFan** [comment]
Thank you for reporting!

If I miss something else, feel free to open another Issue.

Regards
