### ISSUE TITLE
UVCVIDEO GET_DEF errors in dmesg

### ISSUE THREAD

**Issue by ColdBeer72** [mainsail-crew/crowsnest#87]
### What happened

System errors constantly saved in dmesg:
`uvcvideo: Failed to query (GET_DEF) UVC control 1 on unit 2: -32 (exp. 2).`
This is a system with 2 different cameras, both working since 60 days ago without errors.
I detected this problems by system halts and network (wifi usb dongle) disconnections (maybe constant errors can halt the whole USB subsystem). After a few days of checking and testing, I found the problem is with just one of the cameras (let's call it "A camera" because it was the first working on this machine, about 90 days ago).
The other "B camera" gives a different error, but seems to not affect the system:
`3:1: cannot get freq at ep 0x84`
I tried with this uvcvideo quirk but the error is still there:
1. Unload the driver : rmmod uvcvideo
2. Reload the driver with the correct quirks : modprobe uvcvideo quirks=4

### What did you expect to happen

I expected no errors, like 10-15 days ago.

### How to reproduce

Connecting the webcam and you see the trouble coming back to your dmesg.

### Additional information

I know the uvcvideo error is not directly related with crowsnest but.. anyway... maybe someone knows how to bypass or solve the problem (that, I repeat, was not here until a few days ago).

**Comment by KwadFan** [comment]
> I know the uvcvideo error is not directly related with crowsnest but.. anyway... maybe someone knows how to bypass or solve the problem (that, I repeat, was not here until a few days ago).

Yes, right. I am sorry, but this isnt a bug related to crowsnest itself. This is simply an hardware issue on your side and not related to errors in my code. So, please do not use label "bug" if it is not my fault.

This is meant to discuss errors related to my code, not as an general hardware discussion.

Regards Kwad
