### ISSUE TITLE
Crowsnest can not be installed completed using kiauh

### ISSUE THREAD

**Issue by MS1987** [mainsail-crew/crowsnest#91]
### What happened

On my arm64 + armbian platform, I used Kiauh(https://github.com/th33xitus/kiauh) to install crowsnest, it seemed all the steps were finished, but it always show "incomplete" state. And actually, it cannot be used with my camera. This issue has been existed two weeks, hope there any solution.
![image](https://user-images.githubusercontent.com/21118799/221418122-a0a75f24-4730-4910-be65-02ddfefaf2e2.png)

### What did you expect to happen

This issue has been existed two weeks, hope there any solution.

### How to reproduce

Use Kiauh(https://github.com/th33xitus/kiauh) to install crowsnest.

**Comment by meteyou** [comment]
if you use another tool to install crowsnest and the other tools display a state, its not an bug of crowsnest. its a bug of the other tool...
