### ISSUE TITLE
Adding User & Camera Controls to Config

### ISSUE THREAD

**Issue by jk257** [mainsail-crew/crowsnest#92]
### What happened

Can someone please help me understand the syntax for adding Supported Controls to my config. I've tried a whole bunch of different things and nothing is working. 

For example if I want to set a brightness how do I add that to the config?

I've tried simply adding below line 33 brightness = 30 that didnt work. Then I saw people putting things under custom flags so i uncommented that and tried:
brightness=30
brightness:30
-camera-options=brightness=30
-user-controls=brightness=30

but none of those worked. 

![image](https://user-images.githubusercontent.com/77147136/222338316-fd70d8b6-a3db-4246-9a87-a0a867901f5c.png)
![image](https://user-images.githubusercontent.com/77147136/222338459-a60ae7ec-6aa1-4bbe-ab5e-b2747973c75a.png)

### What did you expect to happen

Trying to add parameter to config.

### How to reproduce

Trying to add parameter to config.

**Comment by KwadFan** [comment]
Hey there,

First of all, please read https://github.com/mainsail-crew/crowsnest#foreword.

Then read https://github.com/mainsail-crew/crowsnest#feature-v4l2-control.

If there is further help needed, please see again first link, where to get help.

The issue function is not for misconfiguration (mentioned in foreword) this is only related to Bugs/errors in my code.

Thank you.
Regards Kwad
